name: Update ERDDAP server
on:
  push:
    branches:
      - main
      - development

jobs:
  development_update:
    name: Update Development ERDDAP
    if: ${{github.ref_name}} == 'development'
    runs-on: ubuntu-latest
    steps:
      - name: Update development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          passphrase: ${{ secrets.DEV_SERVER_PASSPHRASE }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: cd  ~/cioos-pacific-erddap/; sh update-erddap.sh --hardFlag
          
  production_update:
    name: Update Production ERDDAP
    if: ${{github.ref_name}} == 'main'
    runs-on: ubuntu-latest
      - name: Update production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          passphrase: ${{ secrets.PROD_SERVER_PASSPHRASE }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: cd  ~/cioos-pacific-erddap/; sh update-erddap.sh --hardFlag
